services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: n8n_db
      POSTGRES_DB: n8n_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n_network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "Asia/Bangkok"
      TZ: "Asia/Bangkok"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_DATABASE: "n8n_db"
      DB_POSTGRESDB_HOST: "172.30.149.151"
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_USER: "postgres"
      DB_POSTGRESDB_SCHEMA: "n8n_schema"
      DB_POSTGRESDB_PASSWORD: "n8n_db"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
      N8N_SECURE_COOKIE: "false"
      N8N_EDITOR_BASE_URL: "https://truman-unexercisable-brielle.ngrok-free.dev"
      WEBHOOK_URL: "https://truman-unexercisable-brielle.ngrok-free.dev"
      NODE_FUNCTION_ALLOW_EXTERNAL: ""
    depends_on:
      - postgres
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    restart: always
    command: http n8n:5678 --url "truman-unexercisable-brielle.ngrok-free.dev"
    environment:
      NGROK_AUTHTOKEN: "338nmwmpQdRAd17LSRQXe2t6foy_2HgiKA6tD3PiQR2k6Q3Dm"
    depends_on:
      - n8n
    networks:
      - n8n_network

  ollma:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama-entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]
    networks:
      - n8n_network

volumes:
  postgres_data:
  n8n_data:
  ollama_data:

networks:
  n8n_network:
    driver: bridge
